apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  book-service: http://book-service:8081
  inventory-service: http://inventory-service:8082
  stock-service: http://stock-service:8083
  config-service: http://config-service:8888
  queue-name: queue