apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service
  labels:
    app: stock-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-service
  template:
    metadata:
      labels:
        app: stock-service
    spec:
      containers:
      - name: stock-service
        image: stock-service
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://stock-service-database:5432/stock_service
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: database-password
        - name: config-service
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: config-service
        - name: book-service
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: book-service
        - name: inventory-service
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: inventory-service
        - name: MQ_QUEUE
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: queue-name
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: mq-user
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: mq-password
---
apiVersion: v1
kind: Service
metadata:
  name: stock-service
spec:
  selector:
    app: stock-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083