server:
  port: 8084
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: inventory
        uri: ${inventory-service:http://localhost:8082}/inventory
        predicates:
        - Path=/inventory/**
      - id: stock
        uri: ${stock-service:http://localhost:8083}/stock
        predicates:
        - Path=/stock/**
      - id: book
        uri: ${book-service:http://localhost:8081}/book
        predicates:
        - Path=/book/**
      - id: author
        uri: ${book-service:http://localhost:8081}/author
        predicates:
        - Path=/author/**
      - id: genre
        uri: ${book-service:http://localhost:8081}/genre
        predicates:
        - Path=/genre/**