server:
  port: 8084
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: inventory
        uri: lb://INVENTORY-SERVICE/inventory
        predicates:
        - Path=/inventory/**
      - id: stock
        uri: lb://STOCK-SERVICE/stock
        predicates:
        - Path=/stock/**
      - id: book
        uri: lb://BOOK-SERVICE/book
        predicates:
        - Path=/book/**
      - id: author
        uri: lb://BOOK-SERVICE/author
        predicates:
        - Path=/author/**
      - id: genre
        uri: lb://BOOK-SERVICE/genre
        predicates:
        - Path=/genre/**