spring:
  application:
    name: STOCK-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_service
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
server:
  port: 8083