spring:
  application:
    name: STOCK-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_service
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
server:
  port: 8083
feign:
  circuitbreaker:
    enabled: true
services:
  book-service: ${book-service:http://localhost:8081}
  inventory-service: ${inventory-service:http://localhost:8082}