services:
  rabbitmq:
    image: rabbitmq:3.9.14-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - network1
  api-gateway:
    build: ../../api-gateway
    ports:
    - 8084:8084
    environment:
      book-service: http://book-service:8081
      inventory-service: http://inventory-service:8082
      stock-service: http://stock-service:8083
    networks:
    - network1
  book-service:
    build: ../../book-service
    networks:
    - network1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://book-service-database:5432/book_service
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
    - book-service-database
  book-service-database:
    image: postgres:14.0
    networks:
    - network1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_service
  inventory-service:
    build: ../../inventory-service
    networks:
      - network1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-service-database:5432/inventory_service
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
    - inventory-service-database
  inventory-service-database:
    image: postgres:14.0
    networks:
      - network1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory_service
  stock-service:
    build: ../../stock-service
    networks:
    - network1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stock-service-database:5432/stock_service
      SPRING_RABBITMQ_HOST: rabbitmq
      book-service: http://book-service:8081
      inventory-service: http://inventory-service:8082
    depends_on:
    - stock-service-database
  stock-service-database:
    image: postgres:14.0
    networks:
    - network1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_service
networks:
  network1: