spring:
  application:
    name: INVENTORY-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_service
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8082
mq:
  queue: queue